<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7575e404-45c6-42e8-9cba-3a37140683ce</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ActiveSync.Host.Abstractions\ActiveSync.Host.Abstractions.csproj" />
    <ProjectReference Include="..\ActiveSync.Host.Composition\ActiveSync.Host.Composition.csproj" />
  </ItemGroup>

</Project>
